### ISSUE TITLE
Shelly MQTT

### ISSUE THREAD

**Issue by JCBond** [exking/udi-mqtt-poly#11]
I am not a programmer, but I have tinkered with coding before. I have been trying to get the MQTT Poly to support Shelly devices, and I have been able to look into the differences and similarities against Sonoff / Tasmota devices.

I have a Shelly1 working as far as controlling the ON and OFF functions, but I am trying to add the Temperature sensor information and that has proven more difficult.

Here is a reference of all the commands the device receives and provides, any help would be appreciated:

https://shelly-api-docs.shelly.cloud/#shelly1-1pm-mqtt

Eventually, I would like to get your Poly to support at least these devices:

https://shelly-api-docs.shelly.cloud/#shelly-h-amp-t-mqtt

https://shelly-api-docs.shelly.cloud/#shelly-motion-mqtt

Attached are the files I have modified so far.
[MQTT.zip](https://github.com/exking/udi-mqtt-poly/files/6233800/MQTT.zip)

**Comment by exking** [comment]
Please submit a pull request with your changes
