### ISSUE TITLE
Ability to support MQTT from sensor that only send numerical value ?

### ISSUE THREAD

**Issue by therealmysteryman** [exking/udi-mqtt-poly#8]
I have created a fork to support sensor using MQTT, that only return a numerical value. I come accross this issue often with device that have support to HA. Instead of returning a structured JSON they only send one message per value. Here an example ( https://github.com/hpeyerl/airthingswave-mqtt )

Not sure if that something you would like to add in the official nodeserver ? Here the class I created. I would prefer running the official release instead of my fork :)

`class MQraw(polyinterface.Node):
    def __init__(self, controller, primary, address, name, device):
        super().__init__(controller, primary, address, name)
        self.cmd_topic = device['cmd_topic']
        self.on = False

    def start(self):
        pass

    def updateInfo(self, payload):
        try :
            self.setDriver('ST', int(payload))
        except Exception as ex :
            LOGGER.error('Failed to parse MQTT Payload: {} {}'.format(ex, payload))

    def query(self, command=None):
        self.controller.mqtt_pub(self.cmd_topic, '')
        self.reportDrivers()

    drivers = [{'driver': 'ST', 'value': 0, 'uom': 56}
              ]   
    
    id = 'MQSR'
    hint = [4, 2, 0, 0]
    commands = {
            'QUERY': query
               }`

**Comment by exking** [comment]
Sure send me a pull request

**Comment by therealmysteryman** [comment]
Thanks :) I have submitted the pull request.

**Comment by therealmysteryman** [comment]
Thanks :)
